### ISSUE TITLE
Problem parsing the XLSX exports from Google Drive

### ISSUE THREAD

**Issue by ovidiubarbu** [doy/spreadsheet-parsexlsx#29]
I create a simple spreadsheet in Google Drive > export it to XLSX and then try to parse it. I get this:

Can't call method "first_child" on an undefined value at /Library/ActivePerl-5.16/lib/Spreadsheet/ParseXLSX.pm line 455.

I have latest version of XML-Twig and Spreadsheed-ParseXLSX.

However, if I open the xlsx file in MSExcel and just re-save it, the file processes just fine!

**Comment by scottbolte** [comment]
I'm seeing the same first_child problem now that Google has converted all my spreadsheets to the 'new & improved' format. I can provide examples if need be.

I also tried the pending pull request from Bob and it did not fix the problem for me.

**Comment by tophopstop** [comment]
Still a problem for me as well, here's another sample file, if it helps.

https://www.dropbox.com/s/foitldsi1k8cgzc/parsexlsxtest.xlsx?dl=0

**Comment by doy** [comment]
Thanks, fixed.

**Comment by tophopstop** [comment]
Great, thanks!  Do you have an ETA for these changes getting out to cpan?

**Comment by tophopstop** [comment]
FWIW- I tried the current repo version of the code and it works great for all the xlsx files I threw at it.
