### ISSUE TITLE
Seems that the Hidden "format" is always '0'

### ISSUE THREAD

**Issue by BigPhiloo** [doy/spreadsheet-parsexlsx#30]
I cannot get correct value for the Hidden property using for instance is_col_hidden() function.
It returns always '0'.

It works when I transform my XLSX into the old XLS format and use only ParseExcel module.

Best Regards,

BigPhiloo

**Comment by doy** [comment]
This is currently unimplemented - I can fix this if you provide me with an example worksheet with some hidden columns.

**Comment by BigPhiloo** [comment]
Hi Doy,
Here is the file and my small script if you need.
Thanks in advance.       De : Jesse Luehrs <notifications@github.com>
 À : doy/spreadsheet-parsexlsx <spreadsheet-parsexlsx@noreply.github.com> 
Cc : BigPhiloo <phil_mahe@yahoo.fr> 
 Envoyé le : Dimanche 15 mars 2015 6h17
 Objet : Re: [spreadsheet-parsexlsx] Seems that the Hidden "format" is always '0' (#30)
   
This is currently unimplemented - I can fix this if you provide me with an example worksheet with some hidden columns.—

**Comment by doy** [comment]
Sorry for the delay (I started a new job recently), but unfortunately Github issue emails don't transmit attachments. Can you upload the file somewhere?

**Comment by doy** [comment]
I'm fairly sure this was fixed in #47 - feel free to reopen if not.
