### ISSUE TITLE
Can't call method "att" on an undefined value at ..../site/lib/Spreadsheet/ParseXLSX.pm line 102

### ISSUE THREAD

**Issue by itzolkmar** [doy/spreadsheet-parsexlsx#32]
Hi,
I found this problem when working with some sheets generated from another program, which is probably not writing down clean XLSX files. The error occurs only with the original files. By rewriting them with Excel it vanishes. As I'm establishing automatic features for daily updates I cannot rewrite them actually.

I found a simple solution that works for me by adding if defined(node); in line 102.

my ($node) = $files->{workbook}->find_nodes('//workbookView');
my $selected = $node->att('activeTab') if defined($node);       # Original: my $selected = $node->att('activeTab');    
$workbook->{SelectedSheet} = defined($selected) ? 0+$selected : 0;

Maybe you could check if this is helpful for your next release!
Kind Regards
itzolkmar

**Comment by doy** [comment]
Can you provide me with a sample worksheet that has this problem?

**Comment by itzolkmar** [comment]
Unfortunately this is internal company stuff. I will try to get a "dummy" version but this could take some time cause I don't have direct contact.

**Comment by melick** [comment]
I am running into the same problem on files from a couple of different database report writers.  Unfortunately my clients have not told me what the packages are that are creating the files this way.  I believe that the programs writing the files do not set the current workbookview.  I can open the file & resave (making no other changes) and the xlsx files load correctly.  itsolkmar's patch did the trick for me.  These files contain confidential data, so I can't forward examples.  And cleaning out the confidential data will cause the value to be defined.

**Comment by dgiordano** [comment]
Hi Experts, I have the same issue.
I attached the xlsx on which I encountered the problem.
The file has been zipped.
Can you kindly investigate into this matter?
Thanks in advance for your cooperation.
Regards.

[xlsx.zip](https://github.com/doy/spreadsheet-parsexlsx/files/120387/xlsx.zip)

**Comment by brerwerb** [comment]
Hi,

Same problem here... @doy any change you can take a look at the attached file?
[problematic.xlsx](https://github.com/doy/spreadsheet-parsexlsx/files/128688/problematic.xlsx)

Thanks in advance,

**Comment by doy** [comment]
The original issue here seems to have been fixed a while ago in #27. The latest two comments here are actually two new, separate bugs (this is a very generic error message), which I have now fixed. I'll get a release out with them in the next couple of days.

**Comment by dgiordano** [comment]
The patch works also for me. Thanks.
