### ISSUE TITLE
Metadata requirement on min perl version does not match the code

### ISSUE THREAD

**Issue by zhouzhen1** [doy/spreadsheet-parsexlsx#33]
While the distributions metadata says perl >= 5.006, however, if we run it with perl 5.8 we can get errors like below. 

Can't modify division (/) in division (/) at /some/path/Spreadsheet/ParseXLSX.pm line 172, near ");"

And latest version of this module actually uses the //= operator which is not available before 5.10. I would suggest change this //= to ||= to support perl 5.8

**Comment by doy** [comment]
I've bumped the perl version requirement to 5.010 for now. If you want to submit a patch to provide pre-5.010 compatibility, I'll probably apply it, but I'm not interested in spending time on it myself.
