### ISSUE TITLE
Information on merged cells is not documented

### ISSUE THREAD

**Issue by Tux** [doy/spreadsheet-parsexlsx#34]
I use the global sheet info for the known merged areas:
<pre>
    $oWkS->{MergedArea}   and $sheet{merged} = [
        map  {  $_->[0] }
        sort {  $a->[1] cmp $b->[1] }
        map  {[ $_, pack "NNNN", @$_          ]}
        map  {[ map { $_ + 1 } @{$_}[1,0,3,2] ]}
        @{$oWkS->{MergedArea}} ];
</pre>
And the cell attribute information on merged cells
<pre>
    $sheet{attr}[$c + 1][$r + 1] = {
        @def_attr,

        type    => lc $oWkC->{Type},
        enc     => $oWkC->{Code},
        merged  => $oWkC->{Merged} || 0,
        hidden  => $FmT->{Hidden}  || 0,
        locked  => $FmT->{Lock}    || 0,
</pre>
Neither is documented, so I am at risk here.

I'd like to see it documented, so I can use it "safe".

**Comment by doy** [comment]
I'm hesitant to document internal implementation details of Spreadsheet::ParseExcel, since they might change in the future (and so then my code would also have to change to retain compatibility, which it can't do if I document it). Are the documented methods `is_merged` and `get_merged_areas` not sufficient?

**Comment by Tux** [comment]
<p>I would have used those if I would have found them in the manual.</p>
<p>None of <tt>man Spreadsheet::ParseExcel</tt>, <tt>man Spreadsheet::ParseXLSX</tt>, <tt>perldoc Spreadsheet::ParseExcel</tt>, and <tt>perldoc Spreadsheet::ParseXLSX</tt> mention <b><i>any</i></b> method for merged cells.</p>

**Comment by Tux** [comment]
See https://github.com/Tux/Spreadsheet-Read/issues/1 for the original report

**Comment by doy** [comment]
https://metacpan.org/pod/Spreadsheet::ParseExcel::Worksheet#get_merged_areas https://metacpan.org/pod/Spreadsheet::ParseExcel::Cell#is_merged

**Comment by Tux** [comment]
I would never have found the first without a reference to it in the top-level docs. Maybe a section about merged cells?

https://github.com/Tux/Spreadsheet-Read/commit/4a2683c61f6c28e7a2da3a1fc79368efae124772 works fine.

**Comment by doy** [comment]
I added references to the Spreadsheet::ParseExcel documentation in 0f73ea7 - I'm not too interested in maintaining a full copy of the Spreadsheet::ParseExcel docs myself, but hopefully this will make them more discoverable.
