### ISSUE TITLE
can't load file from relative path

### ISSUE THREAD

**Issue by garfieldnate** [doy/spreadsheet-parsexlsx#45]
If I pass a relative path to the `parse` method, I get this error:

	IO error: opening ./dir/file.xslx for read : No such file or directory
	 at C:/Strawberry/perl/vendor/lib/Archive/Zip/Archive.pm line 563.
	        Archive::Zip::Archive::read(Archive::Zip::Archive=HASH(0x7bd248), "./dir/file.xslx") called at C:/Strawberry/perl/site/lib/Spreadsheet/ParseXLSX.pm line 35
	        Spreadsheet::ParseXLSX::parse(Spreadsheet::ParseXLSX=HASH(0x7bd0c8), "./dir/file.xslx") called at script.pl line 14
	Can't open file './dir/file.xslx' as a zip file at C:/Strawberry/perl/site/lib/Spreadsheet/ParseXLSX.pm line 35.

**Comment by doy** [comment]
I can't reproduce this, and I believe this is just a typo - I'm guessing the file is actually `./dir/file.xlsx`, not `./dir/file.xslx`. Let me know if that's not the case.
