### ISSUE TITLE
Can not parse some files

### ISSUE THREAD

**Issue by runrig** [doy/spreadsheet-parsexlsx#48]
Found a file which is not being parsed by this library. Opens in Excel, and can be parsed by python's xlrd library (maybe you can use that as a guideline here). First issue I found is when 'Target' attributes start with '/' this lib doesn't handle that. Have not worked through all the issues. Trying to attach sample file...is not letting me attach file here. Got file from anonymous ftp: ftp.pjm.com file: /operations/wind-web-posting/2015-hourly-wind.xls (file is really an xlsx file). Issue just started happening for the last few days, and file is updated daily, so hope you can get the file before format changes again.

**Comment by runrig** [comment]
See commit in my fork.

**Comment by doy** [comment]
This should be fixed by #46.
