### ISSUE TITLE
Tests fail with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [doy/spreadsheet-parsexlsx#49]
t/target-abspath.t fails if perl was compiled with -Duselongdouble:
```
#   Failed test at t/target-abspath.t line 9.
#          got: '10213.575999999999'
#     expected: '10213.576'
# Looks like you failed 1 test of 1.
t/target-abspath.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```
See also http://analysis.cpantesters.org/solved?distv=Spreadsheet-ParseXLSX-0.19 for statistical analysis of test reports.

**Comment by doy** [comment]
Fixed in 5c910b5, thanks!
