### ISSUE TITLE
 Can't call method "read" on an undefined value at /usr/local/share/perl/5.14.2/Spreadsheet/ParseXLSX/Decryptor.pm line 31.,

### ISSUE THREAD

**Issue by mchendriks** [doy/spreadsheet-parsexlsx#52]
After opening a xls file instead of a xlsx file  you get  <Can't call method "read" on an undefined value at /usr/local/share/perl/5.14.2/Spreadsheet/ParseXLSX/Decryptor.pm line 31.>

Is there any way to check if the file is valid before crashing?

**Comment by doy** [comment]
Fixed in 5af52b9.
