### ISSUE TITLE
ä (a umlaut) not imported correctly

### ISSUE THREAD

**Issue by mchendriks** [doy/spreadsheet-parsexlsx#53]
Letters with umlauts are not converted correctly. Is this a setting or a configurable something?

**Comment by doy** [comment]
What do you mean by "converted correctly"? As far as I can tell, letters with umlauts work properly. Do you have a specific example of a thing that doesn't work?

**Comment by doy** [comment]
Closing, since I can't reproduce this issue. Feel free to reopen it (with an example that doesn't work) if you're still having problems.
