### ISSUE TITLE
Add support for scalar ref

### ISSUE THREAD

**Issue by rshadow** [doy/spreadsheet-parsexlsx#59]
Spreadsheet::ParseExcel no need file for parse. I can push scalar ref:
https://github.com/runrig/spreadsheet-parseexcel/blob/master/lib/Spreadsheet/ParseExcel.pm#L634

Please check for scalar ref and parse it to provide compatibility for Spreadsheet::ParseExcel

**Comment by doy** [comment]
Fixed in 0.24!
