### ISSUE TITLE
Use of uninitialized value error

### ISSUE THREAD

**Issue by dgiordano** [doy/spreadsheet-parsexlsx#61]
Dear Experts, I use this module without problems with some files but sometime I encountered this error:

Use of uninitialized value $cell in pattern match (m//) at /usr/local/share/perl5/Spreadsheet/ParseXLSX.pm line 1001.
Use of uninitialized value $col in split at /usr/local/share/perl5/Spreadsheet/ParseXLSX.pm line 1004.
Use of uninitialized value $row in subtraction (-) at /usr/local/share/perl5/Spreadsheet/ParseXLSX.pm line 1010.
Modification of non-creatable array value attempted, subscript -1 at /usr/local/share/perl5/Spreadsheet/ParseXLSX.pm line 410.
 at /usr/local/share/perl5/Spreadsheet/ParseXLSX.pm line 418

I've attached the problematic file.
Can you kindly investigate into this matter?
Thanks in advance for your cooperation.

Regards.

[rates.zip](https://github.com/doy/spreadsheet-parsexlsx/files/366323/rates.zip)

**Comment by doy** [comment]
Fixed in 0.27, thanks!

**Comment by mzavoloka** [comment]
I'm experiencing it as well:

```
Use of uninitialized value $col in split at /usr/local/share/perl/5.22.1/Spreadsheet/ParseXLSX.pm line 1015.
Use of uninitialized value $row in subtraction (-) at /usr/local/share/perl/5.22.1/Spreadsheet/ParseXLSX.pm line 1021.
Use of uninitialized value $col in split at /usr/local/share/perl/5.22.1/Spreadsheet/ParseXLSX.pm line 1015.
Use of uninitialized value $row in subtraction (-) at /usr/local/share/perl/5.22.1/Spreadsheet/ParseXLSX.pm line 1021.
```

```
zavoloka@ptt-zavoloka:~/dev/tests/xls-parsing$ perl -MSpreadsheet::ParseXLSX -le 'print $Spreadsheet::ParseXLSX::VERSION'
0.27

```

**Comment by mzavoloka** [comment]
The module continues to work, but these notifications appear every time I run it with this file:
[problematic-file.xlsx](https://github.com/doy/spreadsheet-parsexlsx/files/669248/problematic-file.xlsx)
