### ISSUE TITLE
Fails with perls < 5.10

### ISSUE THREAD

**Issue by andk** [doy/spreadsheet-parsexlsx#62]
As per subject. Best illustrated with the matrix: 

http://matrix.cpantesters.org/?dist=Spreadsheet-ParseXLSX%200.25

Sample fail report:

http://www.cpantesters.org/cpan/report/1e9f3b48-4a46-11e6-ad66-a31cf8237e7d

Diagnostics: Invalid type '<' in unpack at /tmpfs/.cpan-build-cpansand/2016071500/Spreadsheet-ParseXLSX-0.25-11/blib/lib/Spreadsheet/ParseXLSX/Decryptor.pm line 34.

It would be nice if you could declare your requirement. That way the FAILS would be converted to UNKNOWNS and the user would get feeback earlier, doesn't have to wait for test results. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes 

Thanks,

**Comment by doy** [comment]
Fixed, thanks.
