### ISSUE TITLE
can't call method "read" on an undedefined value at /usr/lib/perl5/site_perl/5.10.0/Spreadsheet/ParseXLSX.pm

### ISSUE THREAD

**Issue by jk1510karti** [doy/spreadsheet-parsexlsx#64]
Hi,

I am getting below error while executing my perl script. Please anyone could assist on this.

can't call method "read" on an undedefined value at usr/lib/perl5/site_perl/5.10.0/Spreadsheet/ParseXLSX.pm line 89

**Comment by jk1510karti** [comment]
Hi,
Its quite urgent, Could someone assist on this.

**Comment by Tux** [comment]
if at all, you need to supply a file that shows this behavior.

**Comment by jk1510karti** [comment]
You mean my source code file?

**Comment by gquipster** [comment]
The Excel spreadsheet you are having problems with

**Comment by jk1510karti** [comment]
I've uploaded the file here. Thanks

http://wikisend.com/download/748862/Book1.xlsx

**Comment by Tux** [comment]
I have no problems whatsoever reading this file on/with

Linux 4.6.2-1-default [openSUSE Tumbleweed (20160422) (x86_64)]
This is perl 5, version 24, subversion 0 (v5.24.0) built for x86_64-linux-thread-multi-ld
Spreadsheet::ParseXLSX-0.25

**Comment by gquipster** [comment]
Hi,

This parses just fine for me on:

Linux 3.16.0-77-generic #99~14.04.1-Ubuntu SMP
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
Spreadsheet::ParseXLSX-0.20

Can you check that you have the latest version of Archive::Zip installed?

**Comment by jk1510karti** [comment]
hi,

thanks for your quick response. I have re-installed Perl version, Everyting is okay now.

**Comment by Gandalf210** [comment]
I had the same issue.
Closing excel while trying to parse the XLSX resolved the problem...
